train:
  TRAIN_DIR: ARVCTRUSS/train/ply_xyzlabelnormal
  VALID_DIR: ARVCTRUSS/valid/ply_xyzlabelnormal
  USE_VALID_DATA: True
  FEATURES: [4,5,6]
  ADD_RANGE: True
  BATCH_SIZE: 8
  EPOCHS: 100
  EPOCH_TIMEOUT: 10
  TERMINATION_CRITERIA: precision # loss, precision, f1_score
  DEVICE: cpu # cuda:X, cpu
  OUTPUT_DIR: saved_models
  TRAIN_SPLIT: 0.8
  LABELS: 3
  NORMALIZE: True
  BINARY: True
  LR: 0.001
  OUTPUT_CLASSES: 1
  THRESHOLD_METHOD: pr # roc, pr, tuning
  LOSS: BCELoss

test:
  TEST_DIR: ARVCTRUSS/test/ply_xyzlabelnormal
  DEVICE: cuda:0
  BATCH_SIZE: 1
  SAVE_PRED_CLOUDS: False
